const BACKGROUND_COLOR = {
    BLACK: 'black',
    WHITE: 'white',
    LIGHT_BLUE: 'lightBlue',
    PRIMARY: 'primary',
    LIGHT_PRIMARY: 'lightPrimary',
    SECONDARY: 'secondary',
    LIGHT_GRAY: 'lightGray',
    MID_GRAY: 'midGray',
    GRAY: 'gray',
    DARK_GRAY: 'darkGray',
    GREEN: 'green',
    LIGHT_GREEN: 'lightGreen',
    DARK_GREEN: 'darkGreen',
    RED: 'red',
    LIGHT_RED: 'lightRed',
    DARK_RED: 'darkRed',
    LIGHT_ORANGE: 'lightOrange',
    ORANGE: 'orange',
    DARK_ORANGE: 'darkOrange',
    YELLOW: 'yellow',
    TRANSPARENT: 'transparent',
};

const FONT_COLOR = {
    BLACK: 'white',
    WHITE: 'black',
    LIGHT_BLUE: 'black',
    PRIMARY: 'white',
    LIGHT_PRIMARY: 'black',
    SECONDARY: 'white',
    LIGHT_GRAY: 'black',
    MID_GRAY: 'black',
    GRAY: 'white',
    DARK_GRAY: 'white',
    GREEN: 'white',
    LIGHT_GREEN: 'black',
    DARK_GREEN: 'white',
    RED: 'white',
    LIGHT_RED: 'black',
    DARK_RED: 'white',
    LIGHT_ORANGE: 'black',
    ORANGE: 'black',
    DARK_ORANGE: 'white',
    YELLOW: 'black',
    TRANSPARENT: 'black',
};

const FONT_COLOR_VALUES = {
    black: 'white',
    white: 'black',
    lightBlue: 'black',
    primary: 'white',
    lightPrimary: 'black',
    secondary: 'white',
    lightGray: 'black',
    midGray: 'black',
    gray: 'white',
    darkGray: 'white',
    green: 'white',
    lightGreen: 'black',
    darkGreen: 'white',
    red: 'white',
    lightRed: 'black',
    darkRed: 'white',
    lightOrange: 'black',
    orange: 'black',
    darkOrange: 'white',
    yellow: 'black',
    transparent: 'black',
};

const ORIENTATION = {
    HORIZONTAL: 'horizontal',
    VERTICAL: 'vertical',
};

export { BACKGROUND_COLOR, FONT_COLOR, FONT_COLOR_VALUES, ORIENTATION };
